# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'centralwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CentralWidget(object):
    def setupUi(self, CentralWidget):
        CentralWidget.setObjectName("CentralWidget")
        CentralWidget.resize(750, 611)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CentralWidget.sizePolicy().hasHeightForWidth())
        CentralWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(CentralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.codeEdit = QtWidgets.QTextEdit(CentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.codeEdit.sizePolicy().hasHeightForWidth())
        self.codeEdit.setSizePolicy(sizePolicy)
        self.codeEdit.setObjectName("codeEdit")
        self.verticalLayout.addWidget(self.codeEdit)
        self.msgEdit = QtWidgets.QTextEdit(CentralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.msgEdit.sizePolicy().hasHeightForWidth())
        self.msgEdit.setSizePolicy(sizePolicy)
        self.msgEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.msgEdit.setObjectName("msgEdit")
        self.verticalLayout.addWidget(self.msgEdit)

        self.retranslateUi(CentralWidget)
        QtCore.QMetaObject.connectSlotsByName(CentralWidget)

    def retranslateUi(self, CentralWidget):
        _translate = QtCore.QCoreApplication.translate
        CentralWidget.setWindowTitle(_translate("CentralWidget", "Form"))
